/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aldrin.ino.gui.panel;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author ALDRIN B. C.
 */
public class JPanelSales extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSales
     */
    public JPanelSales() {
        initComponents();
        putClientProperty(FlatClientProperties.STYLE,
                //                "[light]background: tint(@background,50%);"
                //                + "[dark]background: shade(@background,15%);" +
                "[light]border: 0,0,0,0,shade(@background,10%),,8;"
                + "[dark]border: 0,0,0,0,tint(@background,10%),,8");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Sales");
        add(jLabel1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
