/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aldrin.ino.gui.panel;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ALDRIN B. C.
 */
public class JPanelPayments extends javax.swing.JPanel {

    /**
     * Creates new form JPanelPayments
     */
    public JPanelPayments() {
        initComponents();
        jPanel1.putClientProperty(FlatClientProperties.STYLE,
                //                "[light]background: tint(@background,50%);"
                //                + "[dark]background: shade(@background,15%);" +
                "[light]border: 0,0,0,0,shade(@background,10%),,8;"
                + "[dark]border: 0,0,0,0,tint(@background,10%),,8");
        tableInit();
        jLabelTotal.putClientProperty(FlatClientProperties.STYLE,
                //                "[light]background: tint(@background,50%);"
                //                + "[dark]background: shade(@background,15%);" +
                "[light]border: 0,0,0,0,shade(@background,10%),,8;"
                + "[dark]border: 0,0,0,0,tint(@background,10%),,8");
        jTableSearch.putClientProperty(FlatClientProperties.STYLE,
                //                "[light]background: tint(@background,50%);"
                //                + "[dark]background: shade(@background,15%);" +
                "[light]border: 0,0,0,0,shade(@background,10%),,8;"
                + "[dark]border: 0,0,0,0,tint(@background,10%),,8");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSearch = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonDiscount = new javax.swing.JButton(new FlatSVGIcon("svg/paid.svg"));
        jLabel1 = new javax.swing.JLabel();
        jButtonReturn = new javax.swing.JButton(new FlatSVGIcon("svg/return.svg"));
        jLabel2 = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton(new FlatSVGIcon("svg/edit.svg"));
        jPanelButtons1 = new javax.swing.JPanel();
        jButtonNewDispense = new javax.swing.JButton(new FlatSVGIcon("svg/new.svg"));
        jLabel3 = new javax.swing.JLabel();
        jButtonHold = new javax.swing.JButton(new FlatSVGIcon("svg/hold.svg"));
        jLabel4 = new javax.swing.JLabel();
        jButtonPayment = new javax.swing.JButton(new FlatSVGIcon("svg/paid.svg"));
        jPanel20 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelTotal = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(250, 365));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel12, java.awt.BorderLayout.EAST);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel13.setLayout(new java.awt.BorderLayout());

        jTableSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSearch);

        jPanel13.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanelButtons.setPreferredSize(new java.awt.Dimension(350, 80));
        jPanelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 20));

        jButtonDiscount.setText("<html><center><u>D</u>iscount<br><h4 style=\"color:red; padding:0; margin:0;\">[F7]</h4></center></html>");
        jButtonDiscount.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonDiscount.setPreferredSize(new java.awt.Dimension(90, 42));
        jPanelButtons.add(jButtonDiscount);

        jLabel1.setText("     ");
        jPanelButtons.add(jLabel1);

        jButtonReturn.setText("<html><center><u>R</u>eturn<br><h4 style=\"color:red; padding:0; margin:0;\">[F6]</h4></center></html>");
        jButtonReturn.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonReturn.setPreferredSize(new java.awt.Dimension(90, 42));
        jPanelButtons.add(jButtonReturn);

        jLabel2.setText("     ");
        jPanelButtons.add(jLabel2);

        jButtonEdit.setText("<html><center><u>E</u>dit<br><h4 style=\"color:red; padding:0; margin:0;\">[F5]</h4></center></html>");
        jButtonEdit.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonEdit.setPreferredSize(new java.awt.Dimension(90, 42));
        jPanelButtons.add(jButtonEdit);

        jPanel19.add(jPanelButtons, java.awt.BorderLayout.WEST);

        jPanelButtons1.setPreferredSize(new java.awt.Dimension(350, 80));
        jPanelButtons1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 20));

        jButtonNewDispense.setText("<html><center><u>N</u>ew Dispense<br><h4 style=\"color:red; padding:0; margin:0;\">[F1]</h4></center></html>");
        jButtonNewDispense.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonNewDispense.setPreferredSize(new java.awt.Dimension(110, 42));
        jPanelButtons1.add(jButtonNewDispense);

        jLabel3.setText("     ");
        jPanelButtons1.add(jLabel3);

        jButtonHold.setText("<html><centee><u>H</u>old<br><h4 style=\"color:red; padding:0; margin:0;\">[F2]</h4></center></html>");
        jButtonHold.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonHold.setPreferredSize(new java.awt.Dimension(90, 42));
        jPanelButtons1.add(jButtonHold);

        jLabel4.setText("     ");
        jPanelButtons1.add(jLabel4);

        jButtonPayment.setText("<html><center><u>P</u>ayment<br><h4 style=\"color:red; padding:0; margin:0;\">[Space]</h4></center></html>");
        jButtonPayment.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonPayment.setPreferredSize(new java.awt.Dimension(90, 42));
        jPanelButtons1.add(jButtonPayment);

        jPanel19.add(jPanelButtons1, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel20.setPreferredSize(new java.awt.Dimension(798, 5));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel20, java.awt.BorderLayout.NORTH);

        jPanel11.add(jPanel17, java.awt.BorderLayout.SOUTH);

        jPanel8.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(889, 60));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(350, 80));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabelTotal.setFont(new java.awt.Font("Courier New", 0, 56)); // NOI18N
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotal.setText("123,456.00");
        jPanel10.add(jLabelTotal, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel16.setPreferredSize(new java.awt.Dimension(1048, 5));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel16, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(5, 435));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(899, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(899, 5));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(5, 425));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, java.awt.BorderLayout.LINE_START);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiscount;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHold;
    private javax.swing.JButton jButtonNewDispense;
    private javax.swing.JButton jButtonPayment;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelButtons1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSearch;
    // End of variables declaration//GEN-END:variables


    public DefaultTableModel tableModelSearch = new DefaultTableModel() {
        public Class getColumnClass(int columnIndex) {
            if (columnIndex == 0) {
                return String.class;
            }
            switch (columnIndex) {
                case 1:
                    return String.class;
                case 2:
                    return String.class;
                case 3:
                    return Integer.class;
                default:
                    return String.class;
            }
        }

        public boolean isCellEditable(int row, int col) {
            if (col < 10) {
                return false;

            } else {
                return false;
            }
        }
    };
    private TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableModelSearch);
    private void tableInit() {
        try {
            String[] columnNames = {
                "ID",//
                "PRODUCT",//1
                "UNIT",//2
                "QUANTITY",
                "UNIT PRICE",
                "LINE TOTAL"
            };//15

            jTableSearch.setCellSelectionEnabled(true);
            jTableSearch = new JTable(tableModelSearch);
            JTableHeader header = jTableSearch.getTableHeader();
            header.setPreferredSize(new Dimension(100, 35));
            header.setFont(new Font("Courier New", Font.PLAIN, 16));
//            header.setBackground(new java.awt.Color(0, 102, 153));
//            header.setForeground(new java.awt.Color(0, 102, 153));
            jTableSearch.setRowSorter(sorter);
//            jTableSearch.addMouseListener(this);
            jTableSearch.setRowHeight(30);
            jTableSearch.setFont(new Font("Courier New", Font.PLAIN, 18));
            jScrollPane1.setViewportView(jTableSearch);
            for (int i = 0; i < columnNames.length;) {
                tableModelSearch.addColumn(columnNames[i]);
                i++;
            }
            jScrollPane1.setViewportView(jTableSearch);

            TableColumn[] column = new TableColumn[100];

            column[0] = jTableSearch.getColumnModel().getColumn(0);
            column[0].setPreferredWidth(40);

            column[1] = jTableSearch.getColumnModel().getColumn(1);
            column[1].setPreferredWidth(300);

            column[2] = jTableSearch.getColumnModel().getColumn(2);
            column[2].setPreferredWidth(110);

            TableColumn hidden1 = jTableSearch.getColumnModel().getColumn(0);
            hidden1.setMinWidth(0);
            hidden1.setPreferredWidth(0);
            hidden1.setMaxWidth(0);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
