/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.ino.gui.dialog.au;

import com.aldrin.ino.dao.UserDAO;
import com.aldrin.ino.gui.JFrameInoPOS;
import com.aldrin.ino.model.User;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogAUUser extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAUUser
     */
    private UserDAO userDAO = new UserDAO();
    private User user = new User();
    static String title = "";
    private JFrameInoPOS mainForm;

    public JDialogAUUser(com.aldrin.ino.gui.JFrameInoPOS parent, boolean modal, String title) {
        super(parent, modal);
        this.mainForm = parent;
        initComponents();
        this.title = title;
        this.setTitle(title);
        jButton1.setText("Save");
    }

    public JDialogAUUser(com.aldrin.ino.gui.JFrameInoPOS parent, boolean modal, String title, User u) {
        super(parent, modal);
        initComponents();
        this.mainForm = parent;
        jButton1.setText("Update");
        this.user = u;
        this.title = title;
        this.setTitle(title);
        jTextFieldFirstname.setText(u.getFirstname());
        jTextFieldLastname.setText(u.getLastname());
        jTextFieldUsername.setText(u.getUsername());
        jTextFieldPassword.setText(u.getPassword());
        jButton1.setEnabled(false);

    }

    public JDialogAUUser(com.aldrin.ino.gui.JFrameInoPOS parent, boolean modal, User u, String title) {
        super(parent, modal);
        initComponents();
        this.mainForm = parent;
        jButton1.setText("Delete");
        this.user = u;
        this.title = title;
        this.setTitle(title);
        jTextFieldFirstname.setText(u.getFirstname());
        jTextFieldLastname.setText(u.getLastname());
        jTextFieldUsername.setText(u.getUsername());
        jTextFieldPassword.setText(u.getPassword());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFirstname = new javax.swing.JTextField();
        jTextFieldLastname = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 280, 276, 30));

        jLabel1.setText("Password");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 200, 280, 20));

        jTextFieldFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFirstnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldFirstnameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 40, 280, 30));

        jTextFieldLastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLastnameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 100, 280, 30));

        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 280, 30));

        jTextFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 220, 280, 30));

        jLabel5.setText("Firstname:");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 20, 270, 20));

        jLabel6.setText("Lastname");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, 280, 20));

        jLabel7.setText("Username");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 140, 280, 20));

        setSize(new java.awt.Dimension(345, 369));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (title.equals("New")) {
            try {
                int response = JOptionPane.showConfirmDialog(mainForm, "Are you sure to add a user?", "Add new user", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    this.user.setId(null);
                    this.user.setFirstname(jTextFieldFirstname.getText());
                    this.user.setLastname(jTextFieldLastname.getText());
                    this.user.setUsername(jTextFieldUsername.getText());
                    this.user.setPassword(jTextFieldPassword.getText());
                    User u = userDAO.saveUser(user);
                    JOptionPane.showMessageDialog(rootPane, "The addition of a new user is successfully recorded.");
                    this.dispose();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (title.equals("Update")) {
            try {
                int response = JOptionPane.showConfirmDialog(mainForm, "Are you sure to update a user?", "Update user", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    this.user.setId(user.getId());
                    this.user.setFirstname(jTextFieldFirstname.getText());
                    this.user.setLastname(jTextFieldLastname.getText());
                    this.user.setUsername(jTextFieldUsername.getText());
                    this.user.setPassword(jTextFieldPassword.getText());
                    User u = userDAO.saveUser(user);
                    JOptionPane.showMessageDialog(rootPane, "The updating of a new user is successfully recorded.");
                    this.dispose();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (title.equals("Delete")) {
            try {
                int response = JOptionPane.showConfirmDialog(mainForm, "Are you sure to delete a user?", "Delete user", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    userDAO.delete(user.getId());
                    JOptionPane.showMessageDialog(rootPane, "Deletion of user is successfully recorded!");
                    this.dispose();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldFirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstnameKeyReleased
        userIsUpdated();
    }//GEN-LAST:event_jTextFieldFirstnameKeyReleased

    private void jTextFieldLastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLastnameKeyReleased
        userIsUpdated();
    }//GEN-LAST:event_jTextFieldLastnameKeyReleased

    private void jTextFieldUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyReleased
        userIsUpdated();
    }//GEN-LAST:event_jTextFieldUsernameKeyReleased

    private void jTextFieldPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPasswordKeyReleased
        userIsUpdated();
    }//GEN-LAST:event_jTextFieldPasswordKeyReleased

    private void jTextFieldFirstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstnameKeyPressed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JDialogAUUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JDialogAUUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JDialogAUUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JDialogAUUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialogAUUser dialog = new JDialogAUUser(new com.aldrin.ino.view.JFrameInoPOS(user), true, title);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    private void userIsUpdated() {
        User u = new User(user.getId(), jTextFieldFirstname.getText(), jTextFieldLastname.getText(), jTextFieldUsername.getText(), jTextFieldPassword.getText());
        if (user.toString().equals(u.toString())) {
            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }
    }

}
